---
galaxy_info:
  author: Nainterceptor
  description: Common role used to share basic features between my playbooks
  license: CC-BY
  min_ansible_version: 1.2
  platforms:
    - name: EL
      versions:
        - 7
dependencies: []
